defmodule Wireparty.Repo.Migrations.CreatePartyResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:peers, primary_key: false) do
      add :event_id, references(:events, column: :id, name: "peers_event_id_fkey", type: :uuid),
        null: false

      add :inserted_at, :utc_datetime_usec, null: false
      add :peer_index, :bigint, null: false
      add :assigned_ip, :text, null: false
      add :public_key, :text, null: false
      add :private_key, :text, null: false
      add :label, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:events, primary_key: false) do
      add :organizer_id,
          references(:users, column: :id, name: "events_organizer_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :server_endpoint, :text
      add :interface_name, :text, null: false
      add :subnet_index, :bigint, null: false
      add :listen_port, :bigint, null: false
      add :server_public_key, :text, null: false
      add :server_private_key, :text, null: false
      add :status, :text
      add :slug, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:peers, [:event_id, :peer_index],
             name: "peers_unique_index_per_event_index"
           )

    create unique_index(:peers, [:event_id, :assigned_ip],
             name: "peers_unique_ip_per_event_index"
           )

    create unique_index(:peers, [:event_id, :public_key],
             name: "peers_unique_pubkey_per_event_index"
           )

    create unique_index(:events, [:listen_port], name: "events_unique_port_index")

    create unique_index(:events, [:slug], name: "events_unique_slug_index")

    create unique_index(:events, [:subnet_index], name: "events_unique_subnet_index_index")
  end

  def down do
    drop_if_exists unique_index(:events, [:subnet_index],
                     name: "events_unique_subnet_index_index"
                   )

    drop_if_exists unique_index(:events, [:slug], name: "events_unique_slug_index")

    drop_if_exists unique_index(:events, [:listen_port], name: "events_unique_port_index")

    drop_if_exists unique_index(:peers, [:event_id, :public_key],
                     name: "peers_unique_pubkey_per_event_index"
                   )

    drop_if_exists unique_index(:peers, [:event_id, :assigned_ip],
                     name: "peers_unique_ip_per_event_index"
                   )

    drop_if_exists unique_index(:peers, [:event_id, :peer_index],
                     name: "peers_unique_index_per_event_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `events` table without the `events_organizer_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:events)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `peers` table without the `peers_event_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:peers)
  end
end