defmodule Wireparty.Repo.Migrations.AddRoleToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :role, :text
    end
  end

  def down do
    alter table(:users) do
      remove :role
    end
  end
end